export default [
    [],
    [
        '22+',
        'Kx+',
        'Q2s+',
        'Q5o+',
        'J2s+',
        'J7o+',
        'T2s+',
        'T7o+',
        '93s+',
        '97o+',
        '84s+',
        '86o+',
        '74s+',
        '76o',
        '63s+',
        '65o',
        '53s+',
        '43s',
    ],
    ['22+', 'Ax+', 'K2s+', 'K9o+', 'Q5s+', 'Q9o+', 'J7s+', 'J9o+', 'T7s+', 'T9o', '97s+', '87s', '76s'],
    ['22+', 'A2s+', 'A3o+', 'K4s+', 'K9o+', 'Q8s+', 'QTo+', 'J8s+', 'JTo', 'T8s+', '98s'],
    ['22+', 'A2s+', 'A7o+', 'A5o', 'K6s+', 'KTo+', 'Q8s+', 'QTo+', 'J9s+', 'T9s'],
    ['22+', 'A2s+', 'A8o+', 'K8s+', 'KTo+', 'Q9s+', 'QJo', 'J9s+', 'T8s+', '98s'],
    ['22+', 'A3s+', 'A9o+', 'K9s+', 'KJo+', 'Q9s+', 'QJo', 'J9s+', 'T9s', '98s'],
    ['22+', 'A7s+', 'A5s', 'A4s', 'ATo+', 'K9s+', 'KJo+', 'Q9s+', 'QJo', 'J9s+', 'T9s', '98s'],
    ['22+', 'A8s+', 'A5s', 'ATo+', 'K9s+', 'KJo+', 'Q9s+', 'J9s+', 'T9s'],
    ['22+', 'A9s+', 'ATo+', 'K9s+', 'KQo', 'Q9s+', 'JTs', 'T9s'],
    ['22+', 'A9s+', 'A5s', 'AJo+', 'K9s+', 'KQo', 'QTs+', 'JTs', 'T9s'],
    ['33+', 'A9s+', 'A5s', 'AJo+', 'K9s+', 'KQo', 'QTs+', 'JTs', 'T9s'],
    ['55+', 'A9s+', 'A5s', 'AJo+', 'KTs+', 'KQo', 'QTs+', 'JTs'],
    ['55+', 'ATs+', 'AJo+', 'KTs+', 'QTs+', 'JTs'],
    ['88+', 'A9s+', 'A5s', 'AJo+', 'KTs+', 'KQo', 'QTs+', 'JTs'],
    ['99+', 'A9s+', 'A5s', 'AJo+', 'KTs+', 'KQo', 'QTs+', 'JTs'],
    ['99+', 'ATs+', 'A5s', 'AQo+', 'KTs+', 'QTs+'],
    ['TT+', 'ATs+', 'AJo+', 'KTs+', 'QJs'],
    ['TT+', 'ATs+', 'AJo+', 'KTs+', 'QJs'],
    ['TT+', 'ATs+', 'AQo+', 'KJs+'],
];
