export default [
    [
        '22+',
        'Qx+',
        'J2s+',
        'J3o+',
        'T2s+',
        'T6o+',
        '92s+',
        '96o+',
        '82s+',
        '85o+',
        '73s+',
        '75o+',
        '63s+',
        '65o',
        '52s+',
        '54o',
        '42s+',
    ],
    ['22+', 'Ax+', 'K2s+', 'K7o+', 'Q5s+', 'Q9o+', 'J7s+', 'J9o+', 'T7s+', '97s+', '87s'],
    ['22+', 'Ax+', 'K4s+', 'K9o+', 'Q8s+', 'QTo+', 'J8s+', 'JTo', 'T9s'],
    ['22+', 'A2s+', 'A3o+', 'K6s+', 'K9o+', 'Q8s+', 'QTo+', 'J9s+', 'T9s'],
    ['22+', 'A2s+', 'A4o+', 'K7s+', 'KTo+', 'Q9s+', 'QJo', 'J9s+', 'T8s+', '98s'],
    ['22+', 'A2s+', 'A8o+', 'K7s+', 'KTo+', 'Q9s+', 'QJo', 'J8s+', 'JTo', 'T8s+', '98s', '87s'],
    ['22+', 'A2s+', 'A9o+', 'K9s+', 'KJo+', 'Q9s+', 'QJo', 'J8s+', 'T8s+', '98s'],
    ['22+', 'A2s+', 'ATo+', 'K8s+', 'KJo+', 'Q9s+', 'QJo', 'J9s+', 'T8s+', '98s'],
    ['22+', 'A8s+', 'A5s', 'A4s', 'ATo+', 'K9s+', 'KJo+', 'Q9s+', 'QJo', 'J9s+', 'T9s'],
    ['22+', 'A8s+', 'A5s', 'A4s', 'ATo+', 'K9s+', 'KQo', 'Q9s+', 'J9s+', 'T9s'],
    ['22+', 'A9s+', 'A5s', 'ATo+', 'K9s+', 'KQo', 'QTs+', 'JTs'],
    ['33+', 'A9s+', 'A5s', 'AJo+', 'K9s+', 'KQo', 'QTs+', 'J9s+', 'T9s '],
    ['55+', 'A9s+', 'A5s', 'AJo+', 'K9s+', 'KJo+', 'QTs+', 'JTs'],
    ['44+', 'A9s+', 'A5s', 'AJo+', 'KTs+', 'QTs+', 'JTs'],
    ['88+', 'A8s+', 'A5s', 'A4s', 'A3s', 'AJo+', 'KTs+', 'KQo', 'QTs+', 'JTs'],
    ['99+', 'A9s+', 'A5s', 'AJo+', 'KTs+', 'KQo', 'QTs+', 'JTs'],
    ['99+', 'ATs+', 'A5s', 'AJo+', 'KTs+', 'KQo', 'QTs+', 'JTs'],
    ['99+', 'ATs+', 'A5s', 'AQo+', 'KTs+', 'QTs+'],
    ['TT+', 'ATs+', 'AJo+', 'KTs+', 'QJs'],
    ['TT+', 'ATs+', 'AJo+', 'KJs+', 'QJs'],
];
