export default [
    [
        '22+',
        'Kx+',
        'Q2s+',
        'Q3o+',
        'J2s+',
        'J5o+',
        'T2s+',
        'T6o+',
        '92s+',
        '96o+',
        '84s+',
        '86o+',
        '73s+',
        '76o',
        '63s+',
        '65o',
        '53s+',
        '43s',
    ],
    ['22+', 'Ax+', 'K3s+', 'K9o+', 'Q7s+', 'QTo+', 'J8s+', 'JTo', 'T8s+', '98s'],
    ['22+', 'A2s+', 'A3o+', 'K5s+', 'K9o+', 'Q8s+', 'QTo+', 'J8s+', 'JTo', 'T9s'],
    ['22+', 'A2s+', 'A4o+', 'K7s+', 'KTo+', 'Q9s+', 'QJo', 'J9s+', 'T9s'],
    ['22+', 'A2s+', 'A8o+', 'K7s+', 'KTo+', 'Q9s+', 'QJo', 'J9s+', 'T9s', '98s'],
    ['22+', 'A2s+', 'A9o+', 'K9s+', 'KJo+', 'Q9s+', 'QJo', 'J9s+', 'T9s'],
    ['22+', 'A7s+', 'A5s', 'A4s', 'A3s', 'ATo+', 'K9s+', 'KJo+', 'Q9s+', 'QJo', 'J9s+', 'T9s'],
    ['22+', 'A8s+', 'A5s', 'A4s', 'ATo+', 'K9s+', 'KQo', 'Q9s+', 'J9s+', 'T9s'],
    ['22+', 'A9s+', 'A5s', 'ATo+', 'K9s+', 'KQo', 'QTs+', 'JTs', 'T9s'],
    ['33+', 'A9s+', 'A5s', 'AJo+', 'K9s+', 'KQo', 'QTs+', 'J9s+', 'T9s'],
    ['44+', 'A9s+', 'A5s', 'AJo+', 'KTs+', 'QTs+', 'JTs'],
    ['88+', '66', 'A9s+', 'A5s', 'A4s', 'AJo+', 'KTs+', 'KQo', 'QTs+', 'JTs'],
    ['88+', 'A9s+', 'A5s', 'AJo+', 'KTs+', 'KQo', 'QTs+', 'JTs'],
    ['99+', 'ATs+', 'A5s', 'AJo+', 'KTs+', 'KQo', 'QTs+', 'JTs'],
    ['TT+', 'ATs+', 'AJo+', 'KTs+', 'KQo', 'QJs'],
    ['TT+', 'ATs+', 'AJo+', 'KTs+', 'QJs'],
    ['TT+', 'ATs+', 'AQo+', 'KJs+'],
    ['TT+', 'ATs+', 'AJo+', 'KTs+', 'QJs'],
    ['TT+', 'ATs+', 'AJo+', 'KJs+'],
    ['TT+', 'ATs+', 'AJo+', 'KJs+'],
];
