export default [
    [
        '22+',
        'Kx+',
        'Q2s+',
        'Q3o+',
        'J2s+',
        'J6o+',
        'T2s+',
        'T6o+',
        '92s+',
        '96o+',
        '84s+',
        '86o+',
        '73s+',
        '76o',
        '63s+',
        '65o',
        '52s+',
        '43s',
    ],
    ['22+', 'Ax+', 'K3s+', 'K9o+', 'Q7s+', 'QTo+', 'J8s+', 'JTo', 'T8s+', '98s'],
    ['22+', 'A2s+', 'A7o+', 'A5o', 'K6s+', 'KTo+', 'Q9s+', 'QTo+', 'J9s+', 'T9s'],
    ['22+', 'A2s+', 'A7o+', 'A5o', 'K7s+', 'KTo+', 'Q9s+', 'QJo', 'J9s+', 'T9s'],
    ['22+', 'A2s+', 'A9o+', 'K9s+', 'KJo+', 'Q9s+', 'QJo', 'J9s+', 'T9s'],
    ['22+', 'A7s+', 'A5s', 'A4s', 'A3s', 'ATo+', 'K9s+', 'KJo+', 'Q9s+', 'QJo', 'J9s+', 'T9s'],
    ['22+', 'A8s+', 'A5s', 'ATo+', 'K9s+', 'KQo', 'Q9s+', 'J9s+', 'T9s'],
    ['33+', 'A9s+', 'ATo+', 'K9s+', 'KQo', 'QTs+', 'JTs'],
    ['55+', 'A9s+', 'A5s', 'AJo+', 'K9s+', 'KQo', 'QTs+', 'JTs'],
    ['55+', 'ATs+', 'AJo+', 'KTs+', 'QTs+', 'JTs'],
    ['99+', 'A9s+', 'A5s', 'AJo+', 'KTs+', 'KQo', 'QTs+', 'JTs'],
    ['99+', 'ATs+', 'A5s', 'AJo+', 'KTs+', 'QTs+'],
    ['TT+', 'ATs+', 'AJo+', 'KTs+', 'QJs'],
    ['TT+', 'ATs+', 'AJo+', 'KTs+', 'QJs'],
    ['TT+', 'ATs+', 'AJo+', 'KJs+', 'QJs'],
    ['TT+', 'ATs+', 'AJo+', 'KJs+'],
    ['TT+', 'ATs+', 'AJo+', 'KJs+'],
    ['JJ+', 'ATs+', 'AJo+', 'KJs+'],
    ['JJ+', 'ATs+', 'AJo+', 'KJs+'],
    ['JJ+', 'ATs+', 'AJo+', 'KJs+'],
];
