export default [
    [
        '22+',
        'Kx+',
        'Q2s+',
        'Q4o+',
        'J2s+',
        'J7o+',
        'T2s+',
        'T7o+',
        '93s+',
        '97o+',
        '84s+',
        '86o+',
        '74s+',
        '76o',
        '63s+',
        '53s+',
        '43s',
    ],
    ['22+', 'A2s+', 'A3o+', 'K4s+', 'K9o+', 'Q8s+', 'QTo+', 'J8s+', 'JTo', 'T8s+', '98s'],
    ['22+', 'A2s+', 'A7o+', 'K6s+', 'KTo+', 'Q9s+', 'QTo+', 'J9s+', 'T9s'],
    ['22+', 'A2s+', 'A8o+', 'K9s+', 'KTo+', 'Q9s+', 'JTs', 'T9s'],
    ['22+', 'A3s+', 'ATo+', 'K9s+', 'KJo+', 'Q9s+', 'J9s+', 'T9s'],
    ['22+', 'A8s+', 'A5s', 'A4s', 'ATo+', 'K9s+', 'KQo', 'Q9s+', 'JTs', 'T9s'],
    ['33+', 'A8s+', 'A5s', 'AJo+', 'K9s+', 'KQo', 'QTs+', 'JTs', 'T9s'],
    ['55+', 'ATs+', 'AJo+', 'KTs+', 'QTs+', 'JTs'],
    ['88+', 'A9s+', 'A5s', 'AJo+', 'KTs+', 'KQo', 'QTs+', 'JTs'],
    ['99+', 'A9s+', 'A5s', 'AJo+', 'KTs+', 'QTs+', 'JTs'],
    ['TT+', 'ATs+', 'A5s', 'AJo+', 'KTs+', 'KQo', 'QTs+'],
    ['TT+', 'ATs+', 'AJo+', 'KJs+', 'QJs'],
    ['TT+', 'ATs+', 'AQo+', 'KJs+'],
    ['TT+', 'ATs+', 'AJo+', 'KJs+'],
    ['TT+', 'ATs+', 'AQo+', 'KJs+'],
    ['JJ+', 'ATs+', 'AJo+', 'KJs+'],
    ['JJ+', 'ATs+', 'AJo+', 'KJs+'],
    ['JJ+', 'ATs+', 'AJo+', 'KJs+'],
    ['JJ+', 'ATs+', 'AJo+', 'KJs+'],
    ['QQ+', 'ATs+', 'A5s', 'A4s', 'A3s', 'A2s', 'AQo+', 'KQs'],
];
